POST http://localhost:3333/videos
Content-Type: application/json

{
  "title": "Video 01",
  "description": "Esse é o primeiro vídeo",
  "duration": "180"

}

###

GET  http://localhost:3333/videos

###

PUT http://localhost:3333/videos/
Content-Type: application/json

{
  "title": "Video 01",
  "description": "Esse é o primeiro vídeo",
  "duration": "180"

}